config:
  heading-increment: true
  heading-style: true
  ul-style: true
  list-indent: true
  ul-indent: true
  no-trailing-spaces: true
  no-hard-tabs: true
  no-reversed-links: true
  no-multiple-blanks: true
  line-length: false
  commands-show-output: true
  no-missing-space-atx: true
  no-multiple-space-atx: true
  no-missing-space-closed-atx: true
  no-multiple-space-closed-atx: true
  blanks-around-headings: true
  heading-start-left: true
  no-duplicate-heading: true
  single-title: true
  no-trailing-punctuation: true
  no-multiple-space-blockquote: true
  no-blanks-blockquote: true
  ol-prefix: true
  list-marker-space: true
  blanks-around-fences: true
  blanks-around-lists: true
  no-inline-html: false
  no-bare-urls: false
  hr-style: true
  no-emphasis-as-heading: false
  no-space-in-emphasis: true
  no-space-in-code: true
  no-space-in-links: true
  fenced-code-language: true
  first-line-heading: false
  no-empty-links: true
  required-headings: false
  proper-names: true
  no-alt-text: true
  code-block-style: true
  single-trailing-newline: true
  code-fence-style: true
  emphasis-style: true
  strong-style: true
  link-fragments: true
  reference-links-images: true
  link-image-reference-definitions: true
  link-image-style: true
  table-pipe-style: true
  table-column-count: true
  blanks-around-tables: true
  descriptive-link-text: true
  table-column-style: true
